title: Yang Yang Homepage
page-top-title: Yang Yang Homepage
top-section-bg-text: An NLPer who loves basketball, photography and dance.
home-subtitle: Yang Yang
copyright-text: '&copy; Yang Yang 2025. All Rights Reserved. Last Update: 2025.07'
