
title: Congrui Yin's Homepage
page-top-title: Jerry (Congrui) Yin's Homepage
top-section-bg-text: A NLP & MLSys Nerd
home-subtitle: Jerry (Congrui) Yin (殷骢睿)
copyright-text: '&copy; Congrui Yin 2024. All Rights Reserved.'
